version: '3.9'

volumes:
    postgresql_data:
    redisdata:

services:
    postgresql:
        build:
            context: .
            dockerfile: ./docker/postgresql/Dockerfile
        image: sq_postgresql:1.0
        expose:
            - "5432"
        ports:
            - "5432:5432"
        volumes:
            - "postgresql_data:/var/lib/postgresql/data"
        env_file:
            - "./docker/environments/dev.env"
        hostname: postgresql
        restart: "on-failure"
    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        image: sq_nginx:1.0
        ports:
            - "443:443"
            - "80:80"
        volumes:
            - "./django/media:/srv/media"
            - "./django/static:/srv/static"
            - "./django/secrets:/srv/secrets"
        hostname: simple_questions
        links:
            - django
        restart: "on-failure"
    django:
        build:
            context: .
            dockerfile: ./docker/django/Dockerfile
        image: sq_django:1.0
        ports:
            - "8000:8000"
        volumes:
            - "./django:/srv/django"
            - "./django/media:/srv/media"
            - "./django/static:/srv/static"
            - "./django/secrets:/srv/secrets"
            - "./django/backups:/srv/backups"
        links:
            - postgresql
        env_file:
            - "./docker/environments/dev.env"